site_name: "gridfm-graphkit"
repo_url: https://github.com/gridfm/gridfm-graphkit
site_url: https://gridfm.github.io/gridfm-graphkit/
repo_name: GitHub

nav:
  - Home: index.md
  - Installation: install/installation.md
  - Docker / containers: install/docker.md
  - Getting started:
    - CLI commands: quick_start/quick_start.md
    - YAML configuration file: quick_start/yaml_config.md

theme:
  name: material
  palette:
    primary: white
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.tracking
    - toc.follow
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
  logo: figs/KIT.png
  favicon: figs/KIT.png

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            heading_level: 0
            show_root_heading: false



markdown_extensions:
  - admonition
  - toc:
      permalink: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true
  - md_in_html


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
